# Generated by Django 5.1 on 2024-11-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_new_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={},
        ),
    ]
